name: Daily Feed

on:
  schedule:
    - cron: "30 2 * * *"       # 5:30 AM Bangladesh Time = 5:30 AM UTC
  workflow_dispatch:           # Manual trigger anytime

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install feedparser

      - name: Run main.py (daily only)
        run: python main.py --daily-only

      - name: Ensure daily_feed.xml and last_seen.json exist
        run: |
          if [ ! -f daily_feed.xml ]; then
            echo '<rss version="2.0"><channel><title>Daily Feed</title></channel></rss>' > daily_feed.xml
          fi
          if [ ! -f last_seen.json ]; then
            echo '{"last_seen": null}' > last_seen.json
          fi

      - name: Commit & push daily feed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_feed.xml last_seen.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update daily feed"
            git push
          fi